{{ if has "gerrit" .Values.global.gitProviders }}
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: gerrit-operators-app-release-edp
  annotations:
    chains.tekton.dev/transparency-upload: "true"
  labels:
    {{- include "edp-custom-pipelines.labels" . | nindent 4 }}
spec:
  workspaces:
    - name: shared-workspace
    - name: ssh-creds
  params:
    - name: git-source-url
      default: "https://github.com/epmd-edp/go-go-beego"
      description: git url to clone
      type: string
    - name: git-source-revision
      description: 'git revision to checkout (branch, tag, sha, refâ€¦)'
      default: "master"
      type: string
    - name: codebase-name
      default: "golang-go"
      description: "Project name"
      type: string
    - name: version
      default: "1.0.0"
      description: "Project version"
      type: string
    - name: build-image
      default: "golang:1.20-bullseye"
      description: "Image for build agent"
      type: string
    - name: goproxy
      default: "http://athens-athens-proxy:80"
      description: "goproxy url"
      type: string
    - name: extra-build-commands
      default: "VERSION=$(params.version) make build"
      description: "Command to run build task"
      type: string
    - name: chart-path
      default: "deploy-templates"
      description: "Path to chart directory"
      type: string
    - name: dockerhub-account
      description: "Name of dockerhub account to push images"
      type: string
  tasks:
    - name: init-values
      taskRef:
        kind: Task
        name: init-values
      params:
        - name: CODEBASE_NAME
          value: $(params.codebase-name)
        - name: BRANCH_NAME
          value: $(params.git-source-revision)

    - name: validate-release-branch
      taskRef:
        kind: Task
        name: validate-release-branch
      runAfter:
        - init-values
      params:
        - name: branch
          value: $(params.git-source-revision)

    - name: validate-target-version
      taskRef:
        kind: Task
        name: validate-target-version
      runAfter:
        - init-values
      params:
        - name: version
          value: $(params.version)
        - name: git-source-url
          value: $(params.git-source-url)
      workspaces:
        - name: ssh-directory
          workspace: ssh-creds

    - name: fetch-repository
      taskRef:
        kind: Task
        name: git-clone
      runAfter:
        - validate-release-branch
        - validate-target-version
      params:
        - name: url
          value: $(params.git-source-url)
        - name: revision
          value: $(params.git-source-revision)
        - name: depth
          value: "0"
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: ssh-directory
          workspace: ssh-creds

    - name: update-release-version
      taskRef:
        kind: Task
        name: update-release-version
      runAfter:
        - fetch-repository
      params:
        - name: version
          value: $(params.version)
        - name: chart-path
          value: $(params.chart-path)
        - name: codebase-name
          value: $(params.codebase-name)
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: build
      taskRef:
        kind: Task
        name: build-release
      runAfter:
        - update-release-version
      params:
        - name: base-image
          value: $(params.build-image)
        - name: goproxy
          value: $(params.goproxy)
        - name: extra-commands
          value: $(params.extra-build-commands)
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: kaniko-build
      taskRef:
        kind: Task
        name: kaniko-release
      runAfter:
        - build
      params:
        - name: codebase-name
          value: "$(params.codebase-name)"
        - name: image-tag
          value: "$(params.version)"
        - name: image-tar
          value: "$(params.codebase-name)_$(params.version)"
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: wait-for
      taskRef:
        kind: Task
        name: wait-for
      runAfter:
        - kaniko-build

    - name: helm-push-gh-pages
      taskRef:
        kind: Task
        name: helm-push-gh-release
      runAfter:
        - wait-for
      params:
        - name: CODEBASE_NAME
          value: "$(params.codebase-name)"
        - name: chart-path
          value: $(params.chart-path)
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: git-release-push
      taskRef:
        kind: Task
        name: git-release-push
      runAfter:
        - helm-push-gh-pages
      params:
        - name: branch
          value: $(params.git-source-revision)
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: ssh-directory
          workspace: ssh-creds
{{ end }}
