apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-version-go-default
spec:
  description:
  workspaces:
    - name: source
      description: The workspace consisting of maven project.
  params:
    - name: BRANCH_NAME
      type: string
      description: Codebasebranch name
  results:
    - name: VERSION
      description: "Application version"
    - name: VCS_TAG
      description: "VCS tag"
    - name: IS_TAG
      description: "CodebaseImageStream tag"
    - name: DEPLOYABLE_MODULE_DIR
    - name: TIMESTAMP
      description: Current timestamp
  steps:
    - name: get-timestamp
      image: alpine:3.16
      script: |
        ts=$(date "+%Y%m%d-%H%M%S")
        echo "Current Timestamp: ${ts}"
        echo ${ts} | tr -d "\n" | tee $(results.TIMESTAMP.path)

    - name: get-version
      image: alpine:3.16
      env:
        - name: BRANCH_NAME
          value: "$(params.BRANCH_NAME)"
      workingDir: $(workspaces.source.path)
      script: |
        set -e

        VERSION=$(cat VERSION)

        # get current BUILD ID
        BUILD_ID=$(cat $(results.TIMESTAMP.path))

        BUILD_VERSION="${VERSION}-${BUILD_ID}"
        VCS_TAG="${BRANCH_NAME}-${BUILD_VERSION}"
        NORMALIZED_BRANCH=$(printf '%s' "${BRANCH_NAME}" | sed 's/\//-/g')
        IS_TAG="${NORMALIZED_BRANCH}-${BUILD_VERSION}"

        echo "Application version - ${VERSION}"
        echo "VCS tag - ${VCS_TAG}"
        echo "IS tag - ${IS_TAG}"

        printf "%s" "${VERSION}" > "$(results.VERSION.path)"
        printf "%s" "${VCS_TAG}" > "$(results.VCS_TAG.path)"
        printf "%s" "${IS_TAG}" > "$(results.IS_TAG.path)"

        DEPLOYABLE_MODULE_DIR="."

        printf "%s" "${DEPLOYABLE_MODULE_DIR}" > "$(results.DEPLOYABLE_MODULE_DIR.path)"
