apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: run-clean-gate
spec:
  description: >-
    This task runs a clean gate. It can use a Kubeconfig secret to connect to a remote Kubernetes cluster.
  volumes:
    - name: kubeconfig
      secret:
        secretName: $(params.KUBECONFIG_SECRET_NAME)
        optional: true
  params:
    - name: BASE_IMAGE
      description: The base image for the task (different for buildtools).
      type: string
      default: ""
    - name: EXTRA_COMMANDS
      type: string
      description: Extra commands
      default: ""
    - name: KUBECONFIG_SECRET_NAME
      type: string
      description: The name of secret with Kubeconfig to connect to the remote cluster
      default: "in-cluster"
  steps:
    - name: run
      image: $(params.BASE_IMAGE)
      volumeMounts:
        - name: kubeconfig
          mountPath: /workspace/source/kube
      script: |
        set -ex
        export KUBECONFIG="workspace/source/kube/config"
        $(params.EXTRA_COMMANDS)
