apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sonar-prepare-files-gradle
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Security
    tekton.dev/tags: security
    tekton.dev/displayName: "sonarqube scanner"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    The sonar-prepare-files-gradle Task will copy the files found by git diff
    to a different folder.

  workspaces:
    - name: source
  params:
    - name: CODEBASE_NAME
      type: string
      description: Codebase name.
    - name: BRANCH_NAME
      type: string
      description: Target branch name
    - name: NORMALIZED_BRANCH
      type: string
      description: "Branch name without '/' symbols and lowercase"
    - name: CHANGE_NUMBER
      type: string
      default: ""
      description: Change number from Merge Request
    - name: PATCHSET_NUMBER
      type: string
      default: ""
      description: Patchset number from Merge Request
  results:
    - name: SONAR_PROJECT_KEY
    - name: SONAR_SOURCES
  steps:
    - name: prepare-files
      image: alpine/git:2.36.2
      workingDir: $(workspaces.source.path)
      env:
        - name: CODEBASE_NAME
          value: "$(params.CODEBASE_NAME)"
        - name: BRANCH_NAME
          value: "$(params.BRANCH_NAME)"
        - name: NORMALIZED_BRANCH
          value: "$(params.NORMALIZED_BRANCH)"
        - name: CHANGE_NUMBER
          value: "$(params.CHANGE_NUMBER)"
        - name: PATCHSET_NUMBER
          value: "$(params.PATCHSET_NUMBER)"
        - name: HOME
          value: "$(workspaces.source.path)"
      script: |
        #!/bin/sh

        set -xe
        git config --global --add safe.directory ${HOME}

        echo "[TEKTON] CODEBASE_NAME : ${CODEBASE_NAME}"
        echo "[TEKTON] BRANCH_NAME : ${BRANCH_NAME}"
        echo "[TEKTON] CHANGE_NUMBER : ${CHANGE_NUMBER}"
        echo "[TEKTON] PATCHSET_NUMBER : ${PATCHSET_NUMBER}"
        echo "[TEKTON] NORMALIZED_BRANCH : ${NORMALIZED_BRANCH}"

        export LANG=en_US.utf-8
        git config --local core.quotepath false

        SONAR_SOURCES="codereviewAnalysisRunDir"
        mkdir -p "${SONAR_SOURCES}"

        IFS=$'\n'
        for i in $(git diff --diff-filter=ACMR --name-only origin/"${BRANCH_NAME}")
          do cp --parents "$i" "${SONAR_SOURCES}"/
          echo "file for scanner:" "$i"/
        done
        cp -f build.gradle "${SONAR_SOURCES}"
        cp -fr gradle/ "${SONAR_SOURCES}"
        for build in $(find . -type d -name 'build')
          do cp --parents -r "${build}" "${SONAR_SOURCES}"
        done

        SONAR_PROJECT_KEY="${CODEBASE_NAME}-${NORMALIZED_BRANCH}:change-${CHANGE_NUMBER}-${PATCHSET_NUMBER}"

        printf "%s" "${SONAR_PROJECT_KEY}" > "$(results.SONAR_PROJECT_KEY.path)"
        printf "%s" "${SONAR_SOURCES}" > "$(results.SONAR_SOURCES.path)"
