apiVersion: v1
kind: Secret
metadata:
  name: tekton-edp-interceptor-certs #The edp interceptor relies on this name of the secret for populating certificates.
  labels:
    {{- include "edp-tekton-interceptor.labels" . | nindent 4 }}
# The data is populated at install time by edp interceptor.
